---
name: ci

"on":
  pull_request:
  push:
    branches: [main]

jobs:
  lint-unit:
    uses: sous-chefs/.github/.github/workflows/lint-unit.yml@0.1.0
    permissions:
      actions: write
      checks: write
      pull-requests: write
      statuses: write
      issues: write

  integration:
    needs: lint-unit
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os:
          - 'debian-9'
          - 'debian-10'
          - 'debian-11'
          - 'centos-7'
          - 'centos-8'
          - 'oracle-linux'
          - 'amazon-linux'
          - 'ubuntu-1804'
          - 'ubuntu-2004'
          - 'ubuntu-2204'

        suite:
          - system-install
          - user-install
      fail-fast: false

    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Install Chef
        uses: actionshub/chef-install@main
      - name: test-kitchen
        uses: actionshub/test-kitchen@main
        env:
          CHEF_LICENSE: accept-no-persist
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        with:
          suite: ${{ matrix.suite }}
          os: ${{ matrix.os }}
